apiVersion: v1
kind: Service
metadata:
  name: openam
spec:
  type: NodePort
  ports:
    - port: 80
      name: am80
      targetPort: 8080
    - port: 443
      targetPort: 8443
      name: am443
  selector:
    site: site1
